spring.datasource.url=${CLIENTS_DB_URL:jdbc:mysql://localhost:3306/clientsDb}
spring.datasource.username=${CLIENTS_DB_USERNAME:root}
spring.datasource.password=${CLIENTS_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
